stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

windows-mingw:
  stage: build
  image: "sseemayer/rust-musl-builder-mingw:latest"
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/gib.exe
  script:
    - cargo build --release --target x86_64-pc-windows-gnu