language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
- windows
env:
  global:
  - CRATE_NAME=gib
jobs:
  allow_failures:
  - rust: nightly
  - os: windows
  fast_finish: true
cache: cargo
before_deploy:
  - cargo build --release
  - tar czf $CRATE_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz target/release/$CRATE_NAME
deploy:
  - provider: releases
    token:
      secure: mymrV4loQVIyKj3MVhYQ2b63iLZT+xnE5JXdpC8284LVo469HvqQuywjAG9sEGsjT929NQra+szkAiSog90QOvlVN4nIZPaHlClpRWwWDHJam9clVl7h9+dHy6GY6+gKc6ZTrKWzEhmdX9V0XHB8Q4LPOdjglMsXKuqxp/9VbRxO6ItUhhm1I/hPYkfcKQrpb2jheOLNDcq1GnlFRfdKyLzRlQZfd5XbvMQh1cun1RZ1KdhENB42dC157kr8SFhJY/E1PPC21oT33kdzGEH9y40zgAlWskagzVnWZPmjcoO2+kLPXc/F0+7dDIpQ+2P0zNaG1oHQ/oCQF8rTKsAE1bZvgf4FaJXyAoHeQcL7F0TusVwDEPLSjJ8UfCvBkTnYFXfORtGIxGlTTCcdI/iyHphNpWEU/Go4Z9mpBegFIk/q0mHWd8/tRVIy/tIk2Wly+Y7ZX+hfb2XNpizA9cTNz0C8SFUEH3rgrELNBQgwnEWbt2CWELJg+zDoIwR3UauCOuMXWOLmJoN7OuLEvoFdGFErQjZPXDanoUZad9SBwr+7vJ2LfFYj9PL7MQ4dcmy2OFbmMMHyb+vqjwIvUg/gUfnaz8eqPFdV9zuZuMoJPRaEBcGqmiD+us1T0cakr3rYzQpjJbzJ4fdEvFv5zaKXYh2Ev4fX1UgALtiS9pSmPVQ=
    file: $CRATE_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.*
    on:
      repo: DavSanchez/gib
      condition: $TRAVIS_RUST_VERSION = stable
      tags: true
    edge: true
  - provider: cargo
    token:
      secure: Cg2zlUjPZuDcFNj5yqab+at26vQrYJJYCmXYarUW1mG8k4yP6rCB83OndcTpfVHNgyPmOX5+u58XewHZ1gvODRAtwgvDq9zVAgxZElJR3waBt/CcMQz/k7oVRiw18HFgChkOKLlUe13qbdkgKrFZ8WI2FPgaANJMp0HRswIHqA6xxnbQ8HQuhO49qDiHU8AsbPGVROIJjHq6K1nKW0yzBeAnzoLYXAGpU8j2SnHclK80Fi8b9e/w7if/8aNeEVVbyYaH+MM/A89kivCgdnmX4ig/DYLb8xw2jhwQCGt5Y0QW64CesKxcLGVq+B6pDjo/feM5tclz+p9ZotipiV3RTkkeBSnnOENL2A0SE2L2v8G9gSGPJaugSb0GuACst2y5aWS5gLDCbkAYV5BD8n0xUWIQEAyJSfivg5SLRvthHUF+RGbUt2gRdy9r5dGtNKaldiyG4kVcPxrAOsKEVoFj3WrgbKoLbpLABKBy7gdARc8lQr8F1TGxmlyrEbqaviieJQzuQeypBh+J/r/Wowx+ZPM/7N1o4sTY0/3im+Ld9QhClbgvXkYBRZ7h72aIFtVkIaeU2qGf2BkDM74DqIbzS+yu+q2NQhgJhySehh+Hd6g/rTGPz2anIp8E496njo3TCHX64o7fdeSbMO4xO9Ut241/w0tGtYOy1SJMcfnPd6s=
    on:
      tags: true
    edge: true
