language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows

env:
  global:
    - CRATE_NAME=gib

jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

cache: cargo

deploy:
  - provider: releases
    token:
      secure: WjZu7ij3vUap0jnSKrpdH5rgI/iscq0zmUv1Qlp6dsgoJx4wxE4YLP8yuEOAYry+QOIdoNBvWOjfyh5atNi3lLoWRvunKV3V6ICQMpJ1N32tbID5syjF9ETfKE2Bpnf+s9JYHpuqFJDX7u6O905438MwD1eKOaEleudXI4B1MbhImhineYcn6m9zNikL7h1hCMyCZBYueSBA3/ECk4ExoqU8tF2iDkSklB8+qyk8OiSyvRhT1c6ysE8sgxQUn0De+487Xg01YIkcc5sMFyv9qQurEqQo0fPPS8h+RT56huG422tiYbATL224c6nyJOp0uIl0dx8oXeSYAkkGRwju1JJaOSbSDnHRymKr6q340x9luqVUL6hYH8XRXc4yhNgW1kiEnYgu4K1u7luXKmvx40sIgCNQLffBtkWRKWYLhMPNnCtDBFai+EHraW3GywMfmOnWpupi6qNy3r1sY7sNy1u0MOFnA0N7DJa472FYzPD371s+xvkhg7H7rqUaWcpM8ksXE6jGwc3AJ02eHFfFH+N1bBdOhVpx8rFmpae6GiCRgIjcK94mfg5L/VBB1hu4lQsoOIFpETM7bpyFCtjSTDORlQOAytPqpRZKiTZpE6UXUz/V0WSNENTRKULHwTLrGQyV/c3hmK0yF9SLcaTVaGfDPzg1/TQLrP0Hx1lHWSw=
    file: target/release/gib
    on:
      repo: DavSanchez/gib
      # tags: true
    edge: true
  - provider: cargo
    token:
      secure: ceOmL2hKql3aoWOWdEHehSuxbBidRbfl8QlpZKQq9QEpkbS1hGl5O1TNQBl84QymGig8/90LjnhMKD8oQXPMbr0NWmy7BozXvdKXQF3GLlzdcpwlKkxEWWyQggrdelEYRElaI1ZTzQJgEtfXcgL/PfvLf/7KaL7nLepxpl0LEphmVui3pVNIj44kKsoudEwADHaLlufnqhS9R3HwI4h6myFSz2snXm2iK+Oh48coBTU5VH7qA8cAKjy4jrVuo63eQiT9i66ync19VfOcZe2kuRs+Gy6pT0BRwZpr7NZtsOedwsN38xYUHV90cgIpuAXgYYGfGqPmRcaruFXMSOy0Lsh3j9B3d1CqP9Asz/eRdAMiYfvWG/nS3AA7uV+pwNAFOrWWt2UfYjP3LswQABd/VoyGNVbvqS54vKGAcKP4JIGdGPTmb7eUmG9fXivdz8/EhGjunBzp/TaNJAdnm1dzIvO4lDAAAbYlvkPMo2SOxtV2Zy8iu3aMKwCz0TGNctmNdhFmt/UTxynHJpQbklQJipdhWwCHWfaHEvLoYx9bhKGfzNOYzW8ab3c9nc5kD4SR4iU2uoAuSCqa49N6ysmALDGe0A+ULDF3d1jWeB6+ecUVI3eLJKDdKWO/aWS6UAiqphZohjcmyKYVqUX9vGdSlCdT0SIk038MoIdWc4NcJNE=
    on:
      tags: true
    edge: true
