language: rust
rust:
    - stable
    - beta
    - nightly

os:
    - linux
    - osx
    - windows

env:
  global:
    - CRATE_NAME=gib

jobs:
    allow_failures:
        - rust: nightly
        - os: windows
    fast_finish: true

cache: cargo