language: rust
rust:
    - stable
    - beta
    - nightly

os:
    - linux
    - osx
    - windows

env:
  global:
    - CRATE_NAME=gib

jobs:
    allow_failures:
        - rust: nightly
    fast_finish: true

# matrix:
#     include:
#         # Linux
#         - env: TARGET=aarch64-unknown-linux-gnu
#         - env: TARGET=arm-unknown-linux-gnueabi
#         - env: TARGET=armv7-unknown-linux-gnueabihf
#         - env: TARGET=i686-unknown-linux-gnu
#         - env: TARGET=i686-unknown-linux-musl
#         - env: TARGET=mips-unknown-linux-gnu
#         - env: TARGET=mips64-unknown-linux-gnuabi64
#         - env: TARGET=mips64el-unknown-linux-gnuabi64
#         - env: TARGET=mipsel-unknown-linux-gnu
#         - env: TARGET=powerpc-unknown-linux-gnu
#         - env: TARGET=powerpc64-unknown-linux-gnu
#         - env: TARGET=powerpc64le-unknown-linux-gnu
#         - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
#         - env: TARGET=x86_64-unknown-linux-gnu
#         - env: TARGET=x86_64-unknown-linux-musl

#         # OSX
#         - env: TARGET=i686-apple-darwin
#         os: osx
#         - env: TARGET=x86_64-apple-darwin
#         os: osx

#         # *BSD
#         - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
#         - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
#         - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

#         # Windows
#         - env: TARGET=x86_64-pc-windows-gnu
#         os: windows

#         # Testing other channels
#         - env: TARGET=x86_64-unknown-linux-gnu
#         rust: nightly
#         - env: TARGET=x86_64-apple-darwin
#         os: osx
#         rust: nightly

cache: cargo
# before_cache:
#   # Travis can't cache files that are not readable by "others"
#   - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
#   - chmod -R a+r $HOME/.cargo

# branches:
#   only:
#     # release tags
#     - /^v\d+\.\d+\.\d+.*$/
#     - master

# notifications:
#   email:
#     on_success: never